version: '3'
services:
  webclient:
    container_name: swt_webclient
    image: leoek/swt-webclient:next
    restart: always
    environment:
      - VIRTUAL_HOST=${DOMAIN_CLIENT}
      - VIRTUAL_NETWORK=${NETWORK}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOMAIN_CLIENT}
      - LETSENCRYPT_EMAIL={{ server_mail }}
    networks:
      - proxy-tier

  server:
    container_name: swt_server
    image: leoek/swt-server:next
    restart: always
    environment:
      - VIRTUAL_HOST=${DOMAIN_SERVER}
      - VIRTUAL_NETWORK=${NETWORK}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${DOMAIN_SERVER}
      - LETSENCRYPT_EMAIL={{ server_mail }}
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
    links:
      - db
    networks:
      - proxy-tier
      - backend

  db:
    container_name: swt_server_db
    image: mariadb:10.2.14
    expose:
      - 3306
    restart: always
    env_file:
      - db.env
    volumes:
      - swt_server_db:/var/lib/mysql
    networks: 
      - backend

volumes:
  swt_server_db:

networks:
  proxy-tier:
    external:
      name: ${NETWORK}
  backend:
